### ISSUE TITLE
Markbot keeps requiring different value for font-family 

### ISSUE THREAD

**Issue by akhoinguyen** [akhoinguyen/horizontal-nav#1]
Markbot keeps telling me to fix the value for font-family and that the quotes around the font family Bevan is wrong. Here's the screenshot of Markbot:
<img width="513" alt="markbot-screenshot" src="https://user-images.githubusercontent.com/43136539/46896268-40828f00-ce4a-11e8-9b2b-12a30784f8c0.png">

Please help me out with this @thomasjbradley

**Comment by akhoinguyen** [comment]
Here's my Code in css file:
`h1 {`
  `font-family: "Bevan", cursive;`
 ` color: #fff;`
  `text-align: center;`
  `margin: 0;`
`}`

**Comment by thomasjbradley** [comment]
The problem is the backup font, `Bevan` isn’t a `cursive` font, it’s a `serif` font.

**Comment by akhoinguyen** [comment]
I changed to `serif` but markbot still mark it wrong.

**Comment by thomasjbradley** [comment]
In the screenshot above, Markbot also says to remove the quotes, have you tried that?
`Bevan` doesn’t need quotes because it’s just a single word, only font names with multiple words need quotes to group the words together.

**Comment by akhoinguyen** [comment]
yes i did it and it worked!! thank you so much for your help!
